# This is a basic workflow to help you get started with Actions

name: crea downloaded_artifacts

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Crea la cartella per gli artefatti
        run: mkdir downloaded_artifacts
        
      - name: Commit changes   
        run: |        
          git config --local user.name "domenico-77"
          git config --local user.email "d.vicenti1@studenti.uniba.it"
          git add downloaded_artifacts
          git commit -m "Added downloaded_artifacts"
          git push
