name: prova

on:
  workflow_dispatch:

jobs:
  generate_failure:
    runs-on: ubuntu-latest
    

    steps:
  
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests


      - name: Run Python script 
        run: python3 timer.py


      - name: Sleep for 10 minutes and generates a failure
        run: |
          sleep 600
          python -c "import sys; sys.exit(1)"
