name: Run Python script and save CSV file

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repo
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
    #    cache: 'pip'
    #    cache-dependency-path: '**/requirements.txt'
    #- run: pip install -r requirements.txt
      
    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-

    - name: Install Python dependencies
      if: steps.cache-pip.outputs.cache-hit != 'true'
      run: 
    #    python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Clone repository developersInactivityAnalysis
      run: |
        git clone https://github.com/domenico-77/developersInactivityAnalysis.git
        cd developersInactivityAnalysis
        git checkout tubvic
      # Sostituisci USERNAME con il tuo nome utente GitHub e REPO_NAME con il nome del repository contenente crea_csv.py

    - name: Run Python script
      run: python3 developersInactivityAnalysis/CoreSelection/LocalNonDocCommitExtractor.py https://github.com/MinecraftForge/MinecraftForge.git
      timeout-minutes: 340  # Imposta il timeout per questo passaggio
      # Assicurati che il percorso sia corretto, in base alla posizione del tuo file crea_csv.py nel repository clonato
      
    - name: Archivia i dati come artefatto
      if: ${{ failure() }} #si avvia solo se quello di prima è stato interrotto
      uses: actions/upload-artifact@v2
      with:
       name: LocalNonDocCommitExtractor-artifact
       path: developersInactivityAnalysis/A80_Results/MinecraftForge


    - name: Move CSV file to main repository
      #if: ${{ success() }} #si avvia solo se quello prima ha concluso
      run: | 
        if [ -z "$(find output/MinecraftForge -mindepth 1 -maxdepth 1)" ]; then
           mv developersInactivityAnalysis/A80_Results/MinecraftForge output
        else
           rm output/MinecraftForge
           mv developersInactivityAnalysis/A80_Results/MinecraftForge output
        fi

        
      # Spostiamo il file CSV generato nella directory output del repository principale

    - name: Commit changes
      #if: ${{ success() }} #si avvia solo se quello prima ha concluso
      run: |        
        git config --local user.name "domenico-77"
        git config --local user.email "d.vicenti1@studenti.uniba.it"
        git pull
        git add output
        git commit -m "Add CSV file generated by GitHub Action"
        git push
