name: Run Python script and save CSV file

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specifica la versione di Python desiderata
    
    - name: Install dependencies
      run: |
        python -m pip install pandas
        python -m pip install PyGithub==1.54.1
        python -m pip install GitPython==3.1.31
        python -m pip install PyYAML==5.3.1
    

    - name: Clone repository containing crea_csv.py
      run: git clone https://github.com/collab-uniba/developersInactivityAnalysis.git
      # Sostituisci USERNAME con il tuo nome utente GitHub e REPO_NAME con il nome del repository contenente crea_csv.py
      
    #- name: Install dependencies
    #  run: python -m pip install -r InactivityAnalysis/requirements.txt

    - name: Run Python script
      run: python3 developersInactivityAnalysis/CoreSelection/LocalNonDocCommitExtractor.py https://github.com/JabRef/jabref.git
      # Assicurati che il percorso sia corretto, in base alla posizione del tuo file crea_csv.py nel repository clonato

    - name: Move CSV file to main repository
      run: |

        mv developersInactivityAnalysis/A80_Results/jabref/ output
      # mv InactivityAnalysis output/Cstats.csv
      # Spostiamo il file CSV generato nella directory output del repository principalee

    - name: Commit changes
      run: |
        git config --local user.name "domenico-77"
        git config --local user.email "d.vicenti1@studenti.uniba.it"
        git add --a
        git commit -m "Add CSV file generated by GitHub Action"
        git push
