name: Run Python script and save CSV file

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repo
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x   
        
    - name: Clone repository developersInactivityAnalysis
      run: |
        git clone https://github.com/domenico-77/developersInactivityAnalysis.git
        cd developersInactivityAnalysis
        git checkout tubvic
      
      
    - name: Cache Python dependencies
      uses: actions/cache@v3
      id: cache-pip
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-python-${{ hashFiles('developersInactivityAnalysis/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-

    - name: Install Python dependencies
      run: 
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: python3 developersInactivityAnalysis/CoreSelection/LocalNonDocCommitExtractor.py https://github.com/MinecraftForge/MinecraftForge.git
      timeout-minutes: 340
      
    - name: Archivia i dati come artefatto
      if: ${{ failure() }} #si avvia solo se quello di prima è stato interrotto
      uses: actions/upload-artifact@v2
      with:
       name: LocalNonDocCommitExtractor-artifact
       path: developersInactivityAnalysis/A80_Results/MinecraftForge


    - name: Move CSV file to main repository
      run: | 
        if [ -z "$(find output/MinecraftForge -mindepth 1 -maxdepth 1)" ]; then
           mv developersInactivityAnalysis/A80_Results/MinecraftForge output
        else
           rm -r output/MinecraftForge
           mv developersInactivityAnalysis/A80_Results/MinecraftForge output
        fi

    - name: Commit changes
      run: |        
        git config --local user.name "domenico-77"
        git config --local user.email "d.vicenti1@studenti.uniba.it"
        git pull
        git add output
        git commit -m "Add CSV file generated by GitHub Action"
        git push
