name: Runner RecommenderDevs

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Runner HunterDevGone"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ (github.event.workflow_run.conclusion == 'success' ) }}

    steps:
    - name: Checkout main repo
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x   
        
    - name: Clone repository developersInactivityAnalysis
      run: |
        git clone -b tubvic https://github.com/domenico-77/developersInactivityAnalysis.git
        cd developersInactivityAnalysis
      
      
    - name: Cache Python dependencies
      uses: actions/cache@v3
      id: cache-pip
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-python-${{ hashFiles('developersInactivityAnalysis/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-

    - name: Install Python dependencies
      run: 
        python -m pip install --upgrade pip
        pip install -r requirements.txt


    - name: Run Python script recommender_devs.py
      run: |
        rm -r developersInactivityAnalysis/Resources
        cp -r Resources developersInactivityAnalysis
        python3 developersInactivityAnalysis/Devrecommender/recommender_devs.py ${{ vars.OWNER }} ${{ vars.REPO }} 10 2
      timeout-minutes: 340


    - name: Creating the folder with the current date
      run: mkdir -p pastExecutions/$(date +'%Y-%m-%d')
      
    - name: Move files from output to folder with current date
      run: mv output/* pastExecutions/$(date +'%Y-%m-%d')

    - name: Empty the folder "output" and "support"
      run: |
        rm -rf output/*
        rm -rf support/*
      
    - name: Commit changes
      run: |        
        git config --local user.name "${{ vars.NAME }}"
        git config --local user.email "${{ vars.EMAIL }}"
        git pull
        git add pastExecutions
        git add support
        git add output
        git commit -m "End process"
        git push
