name: Runner LoginIdentifier

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Runner LocalNonDocCommitExtractor", "Second run LocalNonDocCommitExtractor"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout main repo
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x   
        
    - name: Clone repository developersInactivityAnalysis
      run: |
        git clone -b tubvic https://github.com/domenico-77/developersInactivityAnalysis.git
        cd developersInactivityAnalysis
      
      
    - name: Cache Python dependencies
      uses: actions/cache@v3
      id: cache-pip
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-python-${{ hashFiles('developersInactivityAnalysis/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-

    - name: Install Python dependencies
      run: 
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check if there have been other LoginIdentifier executions and recover files
      run: | 
        mkdir -p developersInactivityAnalysis/A80_Results/${{ vars.REPO }}
        if [ -f "output/login_map.csv" ]; then
           echo "There have been other executions, file recovery..."
           mv output/login_map.csv developersInactivityAnalysis/A80_Results/${{ vars.REPO }}
        else
            echo "This is the first execution."
        fi

    - name: Run Python script LoginIdentifier.py
      env:
         MY_SECRET: ${{ secrets.TOKEN }}
      run: |
        cp output/${{ vars.REPO }}/Cstats.csv developersInactivityAnalysis/A80_Results/${{ vars.REPO }}
        python3 developersInactivityAnalysis/CoreSelection/LoginIdentifier.py ${{ vars.OWNER }}/${{ vars.REPO }} $MY_SECRET

        
    - name: Move CSV file to main repository
      run: | 
        if [ -f "output/login_map.csv" ]; then
           rm output/login_map.csv
           mv developersInactivityAnalysis/A80_Results/${{ vars.REPO }}/login_map.csv output
        else
           mv developersInactivityAnalysis/A80_Results/${{ vars.REPO }}/login_map.csv output
        fi

    - name: Commit changes
      run: |        
        git config --local user.name "${{ vars.NAME }}"
        git config --local user.email "${{ vars.EMAIL }}"
        git pull
        git add output
        git commit -m "End LoginIdentifier, saving login_map.csv in output"
        git push
