name: Runner LocalNonDocCommitExtractor

on:
  workflow_dispatch:
 # schedule:
    # Esegui l'azione ogni primo giorno del mese alle 00:00
 #   - cron: '0 0 1 * *'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repo
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x   
        
    - name: Clone repository developersInactivityAnalysis
      run: |
        git clone -b tubvic https://github.com/domenico-77/developersInactivityAnalysis.git
        cd developersInactivityAnalysis
      
      
    - name: Cache Python dependencies
      uses: actions/cache@v3
      id: cache-pip
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-python-${{ hashFiles('developersInactivityAnalysis/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-

    - name: Install Python dependencies
      run: 
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Controlla se ci sono state altre esecuzioni di LocalNonDocCommitExtractor e recupera i file
      run: | 
        if [ -z "$(find output/$REPO -mindepth 1 -maxdepth 1)" ]; then
           echo "Ci sono state altre esecuzioni, recupero i file..."
           mkdir -p developersInactivityAnalysis/A80_Results/$REPO
           mv output/$REPO/commits.csv developersInactivityAnalysis/A80_Results/$REPO
        else
           echo "Questa è la prima esecuzione."
        fi

    - name: Run Python script
      run: python3 developersInactivityAnalysis/CoreSelection/LocalNonDocCommitExtractor.py https://github.com/$OWNER/$REPO.git
      timeout-minutes: 340
      
    - name: Salva i dati temporanei nella cartella di appoggio
      if: ${{ failure() }} #si avvia solo se quello di prima è stato interrotto
      run: |  
        if [ -d "appoggio/$REPO" ]; then
          rm -r appoggio/$REPO
        else
          echo "La directory 'appoggio/$REPO' non esiste."
        fi
        mv developersInactivityAnalysis/A80_Results/$REPO appoggio
        git config --local user.name "domenico-77"
        git config --local user.email "d.vicenti1@studenti.uniba.it"
        git add appoggio/$REPO
        git commit -m "Aggiunto linguist in $REPO"
        git push


    - name: Move CSV file to main repository
      run: | 
        if [ -z "$(find output/$REPO -mindepth 1 -maxdepth 1)" ]; then
           mv developersInactivityAnalysis/A80_Results/$REPO output
        else
           rm -r output/$REPO
           mv developersInactivityAnalysis/A80_Results/$REPO output
        fi
        rm -r appoggio/$REPO

    - name: Commit changes
      run: |        
        git config --local user.name "domenico-77"
        git config --local user.email "d.vicenti1@studenti.uniba.it"
        git pull
        git add output/$REPO
        git commit -m "Terminato LocalNonDocCommitExtractor, aggiunto linguist in output"
        git push
