name: Runner HunterDevGone

on:
  workflow_dispatch:
  #workflow_run:
  #  workflows: ["Runner PullRequestsExtractor"]
  #  types:
  #    - completed

jobs:
  build:
    runs-on: ubuntu-latest
  #  if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout main repo
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x   
        
    - name: Clone repository developersInactivityAnalysis
      run: |
        git clone -b tubvic https://github.com/domenico-77/developersInactivityAnalysis.git
        cd developersInactivityAnalysis
      
      
    - name: Cache Python dependencies
      uses: actions/cache@v3
      id: cache-pip
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-python-${{ hashFiles('developersInactivityAnalysis/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-
    - name: Install Python dependencies
      run: 
        python -m pip install --upgrade pip
        pip install -r requirements.txt

        
    - name: Sposta e rinomina il file
      run: |
        # Sostituisci questi valori con i tuoi percorsi e nomi di file desiderati
        ORIG_PATH=output/${{ vars.OWNER }}
        DEST_PATH=output
        OLD_FILE_NAME=coding_pauses_dates.csv
        NEW_FILE_NAME=pauses_dates_list.csv

        mv "$ORIG_PATH/$OLD_FILE_NAME" "$DEST_PATH/$NEW_FILE_NAME"
      working-directory: ${{ github.workspace }}
      

    - name: Run Python script MissingStuffCollector.py
      run: |
        mkdir -p developersInactivityAnalysis/Organizations/A80API
        mkdir -p developersInactivityAnalysis/Organizations/${{ vars.OWNER }}/${{ vars.REPO }}/
        cp output/pauses_dates_list.csv developersInactivityAnalysis/Organizations/${{ vars.OWNER }}/${{ vars.REPO }}/
        cp output/G_full_list.csv developersInactivityAnalysis/Organizations/A80API
        python3 developersInactivityAnalysis/Devrecommender/HunterDevGone.py
        
      
      #mv developersInactivityAnalysis/Organizations/${{ vars.OWNER }} output
    - name: Move CSV file to main repository
      run: | 
        rm -r output/${{ vars.OWNER }}
        mv developersInactivityAnalysis/Organizations/${{ vars.OWNER }} output
       
    - name: Commit changes
      run: |        
        git config --local user.name "domenico-77"
        git config --local user.email "d.vicenti1@studenti.uniba.it"
        git pull
        git add output
        git commit -m "Fine HunterDevGone, salvataggio di /${{ vars.OWNER }} in output"
        git push
