name: Runner CreateDatasetRecommeder

on:
  workflow_dispatch:
   # schedule:
   #   - cron: '0 11 2 * *'

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout main repo
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x   
        
    - name: Clone repository developersInactivityAnalysis
      run: |
        git clone -b tubvic https://github.com/domenico-77/developersInactivityAnalysis.git
        cd developersInactivityAnalysis
      
      
    - name: Cache Python dependencies
      uses: actions/cache@v3
      id: cache-pip
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-python-${{ hashFiles('developersInactivityAnalysis/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-

    - name: Install Python dependencies
      run: 
        python -m pip install --upgrade pip
        pip install -r requirements.txt


    - name: Run Python script CreateDatasetRecommeder.py
      env:
        MY_SECRET: ${{ secrets.TOKEN }}
      run: python3 developersInactivityAnalysis/Devrecommender/Create_dataset_recommeder.py ${{ vars.OWNER }} ${{ vars.REPO }} $MY_SECRET


    - name: Commit changes
      run: |        
        git config --local user.name "${{ vars.NAME }}"
        git config --local user.email "${{ vars.EMAIL }}"
        git pull
        git add output
        git commit -m "devs_stats.csv saved in output"
        git push
