name: Runner RecommenderDevs

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Runner HunterDevGone"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ (github.event.workflow_run.conclusion == 'success' ) }}

    steps:
    - name: Checkout main repo
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x   
        
    - name: Clone repository developersInactivityAnalysis
      run: |
        git clone -b tubvic https://github.com/domenico-77/developersInactivityAnalysis.git
        cd developersInactivityAnalysis
      
      
    - name: Cache Python dependencies
      uses: actions/cache@v3
      id: cache-pip
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-python-${{ hashFiles('developersInactivityAnalysis/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-

    - name: Install Python dependencies
      run: 
        python -m pip install --upgrade pip
        pip install -r requirements.txt


    - name: Run Python script recommender_devs.py
      run: python3 developersInactivityAnalysis/Devrecommender/recommender_devs.py github ${{ vars.REPO }} 10 2
      timeout-minutes: 340


    - name: Creazione della cartella con la data corrente
      run: mkdir -p pastExecutions/$(date +'%Y-%m-%d')
      
    - name: Sposta i file dall'output alla cartella con la data corrente
      run: mv output/* pastExecutions/$(date +'%Y-%m-%d')

    - name: Svuota la cartella "output" e "appoggio"
      run: |
        rm -rf output/*
        rm -rf appoggio/*
      
    - name: Commit changes
      run: |        
        git config --local user.name "domenico-77"
        git config --local user.email "d.vicenti1@studenti.uniba.it"
        git pull
        git add pastExecutions
        git add output
        git add appoggio
        git commit -m "End process"
        git push
