name: Runner GetA80Lists

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Runner CommitExtractor", "Second run CommitExtractor"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout main repo
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x   
        
    - name: Clone repository developersInactivityAnalysis
      run: |
        git clone -b tubvic https://github.com/domenico-77/developersInactivityAnalysis.git
        cd developersInactivityAnalysis
      
      
    - name: Cache Python dependencies
      uses: actions/cache@v3
      id: cache-pip
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-python-${{ hashFiles('developersInactivityAnalysis/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-

    - name: Install Python dependencies
      run: 
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check if there have been other executions of GetA80Lists and recover files
      run: | 
        mkdir -p developersInactivityAnalysis/A80_Results/${{ vars.REPO }}
        mkdir -p developersInactivityAnalysis/A80MOD_Results/${{ vars.REPO }}
        mkdir -p developersInactivityAnalysis/A80API_Results/${{ vars.REPO }}
        mkdir -p developersInactivityAnalysis/Organizations
        if [ -f "output/A80_devs.csv" ]; then
           echo "There have been other executions, file recovery..."
           mv output/A80_devs.csv developersInactivityAnalysis/A80_Results/${{ vars.REPO }}         
        else
           echo "This is the first execution."
        fi

    - name: Run Python script GetA80Lists.py
      env:
         MY_SECRET: ${{ secrets.TOKEN }}
      run: |
        rm -r developersInactivityAnalysis/Resources
        cp -r Resources developersInactivityAnalysis
        cp -r output/${{ vars.OWNER }} developersInactivityAnalysis/Organizations
        cp output/unmasking_results.csv developersInactivityAnalysis/A80_Results/${{ vars.REPO }}
        python3 developersInactivityAnalysis/CoreSelection/GetA80Lists.py ${{ vars.OWNER }}/${{ vars.REPO }} $MY_SECRET

        
    - name: Move CSV file to main repository
      run: | 
        if [ -f "output/A80_devs.csv" ]; then
           rm output/A80_devs.csv

           mv developersInactivityAnalysis/A80_Results/${{ vars.REPO }}/A80_devs.csv output
           mv developersInactivityAnalysis/A80MOD_Results/${{ vars.REPO }}/A80mod_devs.csv output
           mv developersInactivityAnalysis/A80API_Results/${{ vars.REPO }}/A80api_devs.csv output
        else
           mv developersInactivityAnalysis/A80_Results/${{ vars.REPO }}/A80_devs.csv output
           mv developersInactivityAnalysis/A80MOD_Results/${{ vars.REPO }}/A80mod_devs.csv output
           mv developersInactivityAnalysis/A80API_Results/${{ vars.REPO }}/A80api_devs.csv output
        fi

    - name: Commit changes
      run: |        
        git config --local user.name "${{ vars.NAME }}"
        git config --local user.email "${{ vars.EMAIL }}"
        git pull
        git add output
        git commit -m "End GetA80Lists, saving A80_devs.csv in output"
        git push
