name: Runner CodingTableBuilder

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Runner MissingStuffCollector"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout main repo
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x   
        
    - name: Clone repository developersInactivityAnalysis
      run: |
        git clone -b tubvic https://github.com/domenico-77/developersInactivityAnalysis.git
        cd developersInactivityAnalysis
      
      
    - name: Cache Python dependencies
      uses: actions/cache@v3
      id: cache-pip
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-python-${{ hashFiles('developersInactivityAnalysis/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-

    - name: Install Python dependencies
      run: 
        python -m pip install --upgrade pip
        pip install -r requirements.txt


    - name: Run Python script CodingTableBuilder.py
      env:
         MY_SECRET: ${{ secrets.TOKEN }}
      run: |
        rm -r developersInactivityAnalysis/Resources
        cp -r Resources developersInactivityAnalysis
        mkdir -p developersInactivityAnalysis/logs
        mkdir -p developersInactivityAnalysis/Organizations
        cp -r output/${{ vars.OWNER }} developersInactivityAnalysis/Organizations
        python3 developersInactivityAnalysis/Extractors/CodingTableBuilder.py 

        
    - name: Move CSV file to main repository
      run: | 
           rm -r output/${{ vars.OWNER }}
           mv developersInactivityAnalysis/Organizations/${{ vars.OWNER }} output


    - name: Commit changes
      run: |        
        git config --local user.name "${{ vars.NAME }}"
        git config --local user.email "${{ vars.EMAIL }}"
        git pull
        git add output
        git commit -m "End CodingTableBuilder, saving ${{ vars.OWNER }} in output"
        git push
