name: Second run LocalNonDocCommitExtractor
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Runner LocalNonDocCommitExtractor"]
    types:
      - completed

jobs:
  job_name:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'failure' }}

    steps:
    - name: Checkout main repo
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x   
        
    - name: Clone repository developersInactivityAnalysis
      run: |
        git clone -b tubvic https://github.com/domenico-77/developersInactivityAnalysis.git
        cd developersInactivityAnalysis
      
      
    - name: Cache Python dependencies
      uses: actions/cache@v3
      id: cache-pip
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-python-${{ hashFiles('developersInactivityAnalysis/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-

    - name: Install Python dependencies
      run: 
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: moves from support to developersInactivityAnalysis/A80_Results/${{ vars.REPO }}
      run: |
         mkdir -p developersInactivityAnalysis/A80_Results/${{ vars.REPO }}/
         mv support/${{ vars.REPO }}/commits.csv developersInactivityAnalysis/A80_Results/${{ vars.REPO }}/
      
    - name: Run Python script
      run: python3 developersInactivityAnalysis/CoreSelection/LocalNonDocCommitExtractor.py https://github.com/${{ vars.OWNER }}/${{ vars.REPO }}.git
      timeout-minutes: 340
      
    - name: Save temporary data to support folder
      if: ${{ failure() }} 
      run: |  
        if [ -d "support/${{ vars.REPO }}" ]; then
          rm -r support/${{ vars.REPO }}
        else
          echo "La directory '${{ vars.REPO }}' in 'support' non esiste."
        fi
        mkdir -p support
        mv developersInactivityAnalysis/A80_Results/${{ vars.REPO }} support
        git config --local user.name "domenico-77"
        git config --local user.email "d.vicenti1@studenti.uniba.it"
        git add support
        git commit -m "Add CSV file generated by GitHub Action"
        git push


    - name: Move CSV file to main repository
      run: | 
        if [ -z "$(find output/${{ vars.REPO }} -mindepth 1 -maxdepth 1)" ]; then
           mv developersInactivityAnalysis/A80_Results/${{ vars.REPO }} output
        else
           rm -r output/${{ vars.REPO }}
           mv developersInactivityAnalysis/A80_Results/${{ vars.REPO }} output
        fi

    - name: Commit changes
      run: |        
        git config --local user.name "domenico-77"
        git config --local user.email "d.vicenti1@studenti.uniba.it"
        git pull
        git add output
        git commit -m "Add CSV file generated by GitHub Action"
        git push
