name: Secondo avvio CommitExtractor
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Runner CommitExtractor", "Trigger Secondo avvio CommitExtractor"]
    types:
      - completed

jobs:
  job_name:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'failure'}}

    steps:
    - name: Checkout main repo
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x   
        
    - name: Clone repository developersInactivityAnalysis
      run: |
        git clone -b tubvic https://github.com/domenico-77/developersInactivityAnalysis.git
        cd developersInactivityAnalysis
      
      
    - name: Cache Python dependencies
      uses: actions/cache@v3
      id: cache-pip
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-python-${{ hashFiles('developersInactivityAnalysis/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-

    - name: Install Python dependencies
      run: 
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: sposta da appoggio a developersInactivityAnalysis
      run: |
         mkdir -p developersInactivityAnalysis/logs
         mkdir -p developersInactivityAnalysis/Organizations
         mv appoggio/Commit_Extraction_github.log developersInactivityAnalysis/logs
         mv appoggio/github developersInactivityAnalysis/Organizations
      
    - name: Run Python script
      env:
         MY_SECRET: ${{ secrets.TOKEN }}
      run: python3 developersInactivityAnalysis/Extractors/CommitExtractor.py github-linguist/linguist $MY_SECRET
      timeout-minutes: 340
      
    - name: Salva i dati temporanei nella cartella di appoggio
      if: ${{ failure() }} #si avvia solo se quello di prima è stato interrotto
      run: |  
        if [ -z "$(find appoggio/github -mindepth 1 -maxdepth 1)" ]; then
          rm -r appoggio/github
          rm appoggio/Commit_Extraction_github.log
        else
          echo "La directory 'appoggio/github' non esiste."
        fi
        mv developersInactivityAnalysis/logs/Commit_Extraction_github.log appoggio
        mv developersInactivityAnalysis/Organizations/github appoggio
        git config --local user.name "domenico-77"
        git config --local user.email "d.vicenti1@studenti.uniba.it"
        git add appoggio
        git commit -m "Aggiornati appoggio/github e appoggio/Commit_Extraction_github.log"
        git push


    - name: Move CSV file to main repository
      run: | 
        if [ -z "$(find output/github -mindepth 1 -maxdepth 1)" ]; then
           mv developersInactivityAnalysis/logs/Commit_Extraction_github.log output
           mv developersInactivityAnalysis/Organizations/github output
        else
           rm -r output/github
           rm output/Commit_Extraction_github.log
           mv developersInactivityAnalysis/logs/Commit_Extraction_github.log output
           mv developersInactivityAnalysis/Organizations/github output
        fi


    - name: Commit changes
      run: |        
        git config --local user.name "domenico-77"
        git config --local user.email "d.vicenti1@studenti.uniba.it"
        git pull
        git add output
        git commit -m "Fine estrazione, salvataggio di Commit_Extraction_github.log e /github in output"
        git push
