name: Sposta file e cambia nome

on:
  workflow_dispatch:

jobs:
  move-and-rename:
    runs-on: ubuntu-latest

    steps:
    - name: Check out il repository
      uses: actions/checkout@v2

    - name: Sposta e rinomina il file
      run: |
        # Sostituisci questi valori con i tuoi percorsi e nomi di file desiderati
        ORIG_PATH=repoDiProva/output/${{ vars.OWNER }}
        DEST_PATH=repoDiProva/output
        OLD_FILE_NAME=coding_pauses_dates.csv
        NEW_FILE_NAME=pauses_dates_list.csv

        mv "$ORIG_PATH/$OLD_FILE_NAME" "$DEST_PATH/$NEW_FILE_NAME"
      working-directory: ${{ github.workspace }}

    - name: Esegui il commit e il push delle modifiche
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add "$DEST_PATH/$NEW_FILE_NAME"
        git commit -m "Spostato e rinominato il file"
        git push
