on:
  workflow_run:
    workflows: ["Run Python script and save CSV file"]
    types:
      - completed

jobs:
  job_name:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'failure' }}

    steps:
      - name: Download artifacts (if available)
        uses: actions/download-artifact@v2
        with:
          name: LocalNonDocCommitExtractor-artifact  # Nome dell'artefatto da scaricare, sostituisci con il nome corretto
          path: downloaded_artifacts  # Directory in cui verranno scaricati gli artefatti
          continue-on-error: true

      - name: List artifacts (if available)
        run: |
          if [ -d "downloaded_artifacts" ]; then
          ls downloaded_artifacts
          else
          echo "Nessun artefatto disponibile."
          fi
