name: Trigger Second run PullRequestsExtractor

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Second run PullRequestsExtractor"]
    types:
      - completed

jobs:
  generate_failure:
    runs-on: ubuntu-latest
    
    if: ${{ github.event.workflow_run.conclusion == 'failure'}}

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests


      - name: Sleep for 10 minutes and generates a failure
        run: |
          sleep 600
          python -c "import sys; sys.exit(1)"
