name: Truck-Factor

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repo
      uses: actions/checkout@v3
      
   # - name: Set up Python
  #   uses: actions/setup-python@v4
  #    with:
  #      python-version: 3.x   
        
    - name: Clone repository developersInactivityAnalysis
      run: |
        git clone -b tubvic https://github.com/domenico-77/developersInactivityAnalysis.git
  #      cd developersInactivityAnalysis
      
      
  #  - name: Cache Python dependencies
  #    uses: actions/cache@v3
  #    id: cache-pip
  #    with:
  #      path: ~/.cache/pip
  #      key: ${{ runner.os }}-python-${{ hashFiles('developersInactivityAnalysis/requirements.txt') }}
  #      restore-keys: |
  #        ${{ runner.os }}-python-

  #  - name: Install Python dependencies
  #    run: 
  #      python -m pip install --upgrade pip
  #      pip install -r requirements.txt

        
    - name: install ruby
      run: |
       sudo apt install ruby
       sudo apt-get update -y
       sudo apt-get upgrade -y
       sudo apt-get install -y ruby-rugged
       sudo apt-get install -y ruby-dev
       sudo apt-get install -y build-essential cmake pkg-config libicu-dev zlib1g-dev libcurl4-openssl-dev libssl-dev ruby-dev
       gem install rugged github-linguist --user-install --no-document
         
    

    - name: Run .sh script
      run: |
         cd developersInactivityAnalysis
         mkdir Local_Repositories
         export TERM=xterm
         git clone https://github.com/github-linguist/linguist.git developersInactivityAnalysis/Local_Repositories
         
         cd TruckFactor
         chmod +x commit_log_script.sh
         sh ./commit_log_script.sh developersInactivityAnalysis/Local_Repositories/linguist
         
         chmod +x linguist_script.sh
         sh ./linguist_script.sh developersInactivityAnalysis/Local_Repositories/linguist
         
         java -jar developersInactivityAnalysis/TruckFactor/gittruckfactor.jar developersInactivityAnalysis/Local_Repositories/linguist github-linguist/linguist > output/TF_report.txt
      timeout-minutes: 340


    - name: Move file to main repository
      run: | 
        mv developersInactivityAnalysis/Local_Repositories/linguist output
      #   mv developersInactivityAnalysis/Local_Repositories/linguist/linguistfiles.log output
      #   mv developersInactivityAnalysis/Local_Repositories/linguist/commitinfo.log output
      #   mv developersInactivityAnalysis/Local_Repositories/linguist/commitfileinfo.log output
      #   mv developersInactivityAnalysis/Local_Repositories/linguist/filelist.log output


    - name: Commit changes
      run: |        
        git config --local user.name "domenico-77"
        git config --local user.email "d.vicenti1@studenti.uniba.it"
        git pull
        git add output
        git commit -m "Terminato Truck-Factor, aggiunto TF_report.txt in output"
        git push
        
  
